---
title: "FISH with EdU labelling"
lab: "Andrew Belmont Laboratory"
author: "Omid Gholamalamdari"
date: "August 24, 2018"
output:
  pdf_document: default
  html_document: default
bibliography: bib.bib
csl: nature.csl
---

# Introduction

DNA Fluorescent In-Situ Hybridization (FISH) is a technique to visualize stretches of chromatin
in fixed cells the technique has been originally developed in the early 80s [@Langer-Safer] and
extensively optimized by Cremer lab[@Solovei2002; @Solovei2010 ;@Markaki].
This protocol describes the combination of EdU labeling (as a marker for cell cycle stage) and
3D DNA-FISH in HCT116 cells, but with optimization can be used for all adherent cells.

# Materials
All buffers should be filtered before use to reduce the noise from floating particles.
This is specially important for the buffers containing 

+ DIG and/or biotin labelled probes
+ 
+ 
+ 
+ 
+

# Procedure
## Cell Seeding
Cells seeded at 0.6e6/ml, 0.5 ml culture media well.

## EdU Pulse
EdU pusled (A:C)*(1:4) by replacing with the media containing EdU( 5mM).
6.5µl 10mM EdU in 13 ml media.
Pulsed for 10 minutes.

## Cell Fixation
1. Rinse cells 3 times, with warm(37&deg;C).
2. Transfer coverslips to a new 24 well plate containing warm PBS. 
    + This is to leave behind all the debris from the cells attached to plate.
3. Fix with 3% PFA in 1X PBS for 10 min at RT.
    + After this step you either need to gradually exchange PFA with PBS, or quench it with PBS-Glycine really quick.
4. Quench with 0.5M Glycine-PBS for 5 min at RT.
5. Permeabilize with 0.5% Tx-10 in PBS. 10 min at RT.
6. Rinse the cells with PBS, 3 times.
7. Incubate cells in 20% Gylcerol in PBS for 2 hr at RT.
8. Freeze the cells by dipping in liquid nitrogen and thaw on a paper towel or kimwipe.
    + Once the cells are thawed put back in PBS-Glycerol.
    + Repeat freeze-thaw cycle 4 times.
9. Wash cells in PBST 3 x 10 minutes at RT.
10. Rinse the cells with 0.1 N HCl in DW and incubate with fresh portion for 10 min at RT.
11. Wash cells with 2XSSC 3x 5 minutes at RT.
12. Incubate in 2XSSC/50% Formamide at 4$deg;C.
    + Incubated at least overnight.
    + Cells can be stored in 2XSSC/50% formamide for month.
    + The more cells stay in formamide, the more chromatin decondenses.

## Hybridization
This protocol denatures the chromatin and the probe at the same time on a heat block.
1. Make the hybridization mixture as below
  |----------------------------------------------------------|-----------------|
  |1. DIG and/or biotin labelled probes dissolved in HYB buffer  | 80-100 ng (each)|
  |2. Human COT1 DNA | 1000 ng |
  |----------------------------------------------------------|----------------|
  |Make to 4 $\mu l$ with HYB buffer| Total 4 $\mu l$|
2. Drop 4 $\mu l$ of the mixture on a microscopic slide.
3. Take 1 coverslip out of 2XSSC/Formamide.
    + Remove the excess solution by tapping the edge of the coverslip on kimwipe.
    + Place the coverslip on the HYB mixture.
    + Seal with rubber cement and wait for it to dry.
    + Rubber cement will turn clear when it's dry. 
4. Denature on a 77 &deg;C on a heatblock or 
## Probe washes

## Probe staining

## Click reaction

## Counterstaining with DAPI

## Mounting

## References













